### ISSUE TITLE
Is there any better place for this functionality?

### ISSUE THREAD

**Issue by beleran** [mitaxe/crew-applications#4]
https://github.com/mitaxe/crew-applications/blob/0bbb3a7acfab0770fe6f5862abf1564fcdd27f86/src/utils/boardUtils.js#L3

**Comment by mitaxe** [comment]
What could you suggest? I have chosen utils because it is an independent function and it is easy to cover it tests

**Comment by beleran** [comment]
Utils for me is something like DB connectors or archivers.
In this case it might be a service, however i'm not sure that it should be.
What other place you might propose in terms of classic react app structure?

**Comment by mitaxe** [comment]
As another option, it can be placed in actions. If you are talking about classic react app structure with redux

**Comment by beleran** [comment]
Sounds good, thank you.
